export type HttpMethod = "GET" | "POST" | "PATCH" | "PUT" | "DELETE";

export type ApiEndpoint = {
  id: string;
  name: string;
  method: HttpMethod;
  /** Path under /api — use {hackathonId}, {id}, etc. as placeholders */
  pathTemplate: string;
  description?: string;
  sampleBody?: string;
  requiresHackathonId?: boolean;
  requiresId?: boolean;
  requiresExtraId?: boolean;
  extraIdLabel?: string;
};

export type ApiEndpointGroup = {
  id: string;
  title: string;
  description: string;
  endpoints: ApiEndpoint[];
};

/**
 * Catalog of allowed HAS BFF endpoints.
 * Backend may only be user/login (auth UI) + haas/* (this list).
 */
export const API_ENDPOINT_GROUPS: ApiEndpointGroup[] = [
  {
    id: "hackathons",
    title: "1. Hackathons (CRUD)",
    description: "Create, list, update, archive, and restore events.",
    endpoints: [
      {
        id: "hackathons-list",
        name: "List hackathons",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/",
        description: "Query: search, is_active, show_deleted, start_after, end_before",
      },
      {
        id: "hackathons-create",
        name: "Create hackathon",
        method: "POST",
        pathTemplate: "/api/haas/hackathons/",
        description: "Root / system.admin only",
        sampleBody: JSON.stringify(
          {
            name: "National CTF 2026",
            display_name: "National CTF",
            description: "",
            city: null,
            start_datetime: "2026-09-01T09:00:00+05:00",
            end_datetime: "2026-09-03T18:00:00+05:00",
            is_infinite: false,
            is_active: true,
            view_on_dashboard: false,
            discord_link: "",
          },
          null,
          2,
        ),
      },
      {
        id: "hackathons-get",
        name: "Get hackathon",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/",
        description: "Includes modules + my_roles",
        requiresHackathonId: true,
      },
      {
        id: "hackathons-patch",
        name: "Update hackathon",
        method: "PATCH",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/",
        description: "Organizer / operators",
        requiresHackathonId: true,
        sampleBody: JSON.stringify(
          {
            display_name: "Updated name",
            description: "Updated description",
            is_active: true,
          },
          null,
          2,
        ),
      },
      {
        id: "hackathons-archive",
        name: "Archive hackathon",
        method: "POST",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/archive/",
        description: "Soft-delete event",
        requiresHackathonId: true,
      },
      {
        id: "hackathons-restore",
        name: "Restore hackathon",
        method: "POST",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/restore/",
        description: "Undo archive",
        requiresHackathonId: true,
      },
      {
        id: "hackathons-break-glass",
        name: "Break glass",
        method: "POST",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/break-glass/",
        description: "System operator emergency access",
        requiresHackathonId: true,
        sampleBody: JSON.stringify({ reason: "Customer outage" }, null, 2),
      },
    ],
  },
  {
    id: "session",
    title: "2. Session",
    description: "Current user bootstrap.",
    endpoints: [
      {
        id: "me",
        name: "Me",
        method: "GET",
        pathTemplate: "/api/haas/me/",
        description: "User + system_role + hackathon_roles",
      },
    ],
  },
  {
    id: "system",
    title: "3. System",
    description: "Platform admins, users, audit, stats.",
    endpoints: [
      {
        id: "system-stats",
        name: "Platform stats",
        method: "GET",
        pathTemplate: "/api/haas/system/stats/",
        description: "Counts across the platform",
      },
      {
        id: "system-admins-list",
        name: "List system admins",
        method: "GET",
        pathTemplate: "/api/haas/system/admins/",
        description: "Root only",
      },
      {
        id: "system-admins-create",
        name: "Grant system admin",
        method: "POST",
        pathTemplate: "/api/haas/system/admins/",
        description: "Root only",
        sampleBody: JSON.stringify(
          { user: "<user-uuid>", notes: "", role: "system.admin" },
          null,
          2,
        ),
      },
      {
        id: "system-admins-delete",
        name: "Revoke system admin",
        method: "DELETE",
        pathTemplate: "/api/haas/system/admins/{id}/",
        description: "Root only",
        requiresId: true,
      },
      {
        id: "system-users",
        name: "List global users",
        method: "GET",
        pathTemplate: "/api/haas/system/users/",
        description: "Query: search, is_block",
      },
      {
        id: "system-users-block",
        name: "Block global user",
        method: "POST",
        pathTemplate: "/api/haas/system/users/{id}/block/",
        description: "Global account block",
        requiresId: true,
        sampleBody: JSON.stringify({ reason: "Support block" }, null, 2),
      },
      {
        id: "system-users-unblock",
        name: "Unblock global user",
        method: "POST",
        pathTemplate: "/api/haas/system/users/{id}/unblock/",
        requiresId: true,
      },
      {
        id: "system-audit",
        name: "System audit logs",
        method: "GET",
        pathTemplate: "/api/haas/system/audit/",
        description: "Query: hackathon, action, category, actor",
      },
      {
        id: "system-activity",
        name: "System activity logs",
        method: "GET",
        pathTemplate: "/api/haas/system/activity/",
        description: "Query: type, user, hackathon",
      },
    ],
  },
  {
    id: "catalog",
    title: "4. Catalog",
    description: "Global challenge metadata catalogs.",
    endpoints: [
      {
        id: "catalog-types",
        name: "Challenge types",
        method: "GET",
        pathTemplate: "/api/haas/catalog/challenge-types/",
      },
      {
        id: "catalog-difficulties",
        name: "Difficulties",
        method: "GET",
        pathTemplate: "/api/haas/catalog/difficulties/",
      },
      {
        id: "catalog-categories",
        name: "Categories",
        method: "GET",
        pathTemplate: "/api/haas/catalog/categories/",
      },
      {
        id: "catalog-sources",
        name: "Sources",
        method: "GET",
        pathTemplate: "/api/haas/catalog/sources/",
      },
      {
        id: "catalog-hints",
        name: "Hints",
        method: "GET",
        pathTemplate: "/api/haas/catalog/hints/",
      },
    ],
  },
  {
    id: "event-config",
    title: "5. Event config",
    description: "Settings, modules, rules, scoring, playing, analytics.",
    endpoints: [
      {
        id: "settings-get",
        name: "Get settings",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/settings/",
        requiresHackathonId: true,
      },
      {
        id: "settings-patch",
        name: "Update settings",
        method: "PATCH",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/settings/",
        requiresHackathonId: true,
        sampleBody: JSON.stringify({ broadcast_message: "Hello teams" }, null, 2),
      },
      {
        id: "modules-get",
        name: "Get modules",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/modules/",
        requiresHackathonId: true,
      },
      {
        id: "modules-patch",
        name: "Update modules",
        method: "PATCH",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/modules/",
        requiresHackathonId: true,
        sampleBody: JSON.stringify(
          {
            jeopardy_enabled: true,
            koth_enabled: false,
            attack_defence_enabled: false,
            viewer_can_export: false,
          },
          null,
          2,
        ),
      },
      {
        id: "user-rules-get",
        name: "Get user rules",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/user-rules/",
        requiresHackathonId: true,
      },
      {
        id: "user-rules-patch",
        name: "Update user rules",
        method: "PATCH",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/user-rules/",
        requiresHackathonId: true,
        sampleBody: JSON.stringify(
          { max_attempts: 0, spawn_limit: 0, vpn_allowed: true },
          null,
          2,
        ),
      },
      {
        id: "scoring-config",
        name: "Scoring config",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/scoring-config/",
        requiresHackathonId: true,
      },
      {
        id: "scoring-config-patch",
        name: "Update scoring config",
        method: "PATCH",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/scoring-config/",
        requiresHackathonId: true,
        sampleBody: JSON.stringify({}, null, 2),
      },
      {
        id: "playing",
        name: "Playing control",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/playing/",
        requiresHackathonId: true,
      },
      {
        id: "playing-patch",
        name: "Update playing flags",
        method: "PATCH",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/playing/",
        requiresHackathonId: true,
        sampleBody: JSON.stringify({ is_open: true, is_active: true }, null, 2),
      },
      {
        id: "playing-challenges-list",
        name: "Live challenge roster",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/playing/challenges/",
        requiresHackathonId: true,
      },
      {
        id: "playing-challenges-add",
        name: "Add to live challenge roster",
        method: "POST",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/playing/challenges/",
        requiresHackathonId: true,
        sampleBody: JSON.stringify({ challenge_ids: ["<uuid>"] }, null, 2),
      },
      {
        id: "playing-challenges-remove",
        name: "Remove from live challenge roster",
        method: "DELETE",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/playing/challenges/{id}/",
        requiresHackathonId: true,
        requiresId: true,
      },
      {
        id: "playing-teams-list",
        name: "Live team roster",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/playing/teams/",
        requiresHackathonId: true,
      },
      {
        id: "playing-teams-add",
        name: "Add to live team roster",
        method: "POST",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/playing/teams/",
        requiresHackathonId: true,
        sampleBody: JSON.stringify({ team_ids: ["<uuid>"] }, null, 2),
      },
      {
        id: "playing-teams-remove",
        name: "Remove from live team roster",
        method: "DELETE",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/playing/teams/{id}/",
        requiresHackathonId: true,
        requiresId: true,
      },
      {
        id: "analytics",
        name: "Analytics",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/analytics/",
        requiresHackathonId: true,
      },
      {
        id: "analytics-export",
        name: "Analytics export (CSV)",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/analytics/export/",
        requiresHackathonId: true,
      },
      {
        id: "report-user",
        name: "User report",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/reports/users/{id}/",
        requiresHackathonId: true,
        requiresId: true,
      },
      {
        id: "report-team",
        name: "Team report",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/reports/teams/{id}/",
        requiresHackathonId: true,
        requiresId: true,
      },
    ],
  },
  {
    id: "groups-permissions",
    title: "10. Groups & permissions",
    description: "Django Groups primary permission model (§13).",
    endpoints: [
      {
        id: "permissions-list",
        name: "Permission catalog",
        method: "GET",
        pathTemplate: "/api/haas/permissions/",
      },
      {
        id: "groups-list",
        name: "List platform groups",
        method: "GET",
        pathTemplate: "/api/haas/groups/",
      },
      {
        id: "groups-create",
        name: "Create platform group",
        method: "POST",
        pathTemplate: "/api/haas/groups/",
        sampleBody: JSON.stringify(
          {
            name: "HaaS Platform Operator",
            description: "",
            hackathon: null,
            can_manage_groups: false,
            permission_ids: [],
            user_ids: [],
          },
          null,
          2,
        ),
      },
      {
        id: "groups-assign",
        name: "Assign users to group",
        method: "POST",
        pathTemplate: "/api/haas/groups/{id}/assign-users/",
        requiresId: true,
        sampleBody: JSON.stringify(
          { user_ids: ["<uuid>"], remove: false },
          null,
          2,
        ),
      },
      {
        id: "event-groups-list",
        name: "List event groups",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/groups/",
        requiresHackathonId: true,
      },
      {
        id: "event-groups-create",
        name: "Create event group",
        method: "POST",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/groups/",
        requiresHackathonId: true,
        sampleBody: JSON.stringify(
          {
            name: "Event Managers",
            description: "",
            can_manage_groups: false,
            permission_ids: [],
            user_ids: [],
          },
          null,
          2,
        ),
      },
      {
        id: "event-groups-assign",
        name: "Assign users to event group",
        method: "POST",
        pathTemplate:
          "/api/haas/hackathons/{hackathonId}/groups/{id}/assign-users/",
        requiresHackathonId: true,
        requiresId: true,
        sampleBody: JSON.stringify(
          { user_ids: ["<uuid>"], remove: false },
          null,
          2,
        ),
      },
    ],
  },
  {
    id: "roles-members",
    title: "6. Roles & members",
    description: "Event staff bindings and memberships.",
    endpoints: [
      {
        id: "roles-list",
        name: "List roles",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/roles/",
        requiresHackathonId: true,
      },
      {
        id: "roles-create",
        name: "Create role binding",
        method: "POST",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/roles/",
        requiresHackathonId: true,
        sampleBody: JSON.stringify(
          { user: "<user-uuid>", role: "hackathon.manager", expires_at: null },
          null,
          2,
        ),
      },
      {
        id: "roles-patch",
        name: "Update role binding",
        method: "PATCH",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/roles/{id}/",
        requiresHackathonId: true,
        requiresId: true,
        sampleBody: JSON.stringify({ is_active: true }, null, 2),
      },
      {
        id: "roles-delete",
        name: "Revoke role binding",
        method: "DELETE",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/roles/{id}/",
        requiresHackathonId: true,
        requiresId: true,
      },
      {
        id: "members-list",
        name: "List members",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/members/",
        requiresHackathonId: true,
      },
      {
        id: "members-create",
        name: "Add member",
        method: "POST",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/members/",
        requiresHackathonId: true,
        sampleBody: JSON.stringify({ user: "<user-uuid>", player_label: "" }, null, 2),
      },
      {
        id: "members-create-user",
        name: "Create event user",
        method: "POST",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/members/create-user/",
        requiresHackathonId: true,
        sampleBody: JSON.stringify(
          { email: "player@example.com", name: "Player", password: "ChangeMe123!" },
          null,
          2,
        ),
      },
      {
        id: "members-patch",
        name: "Update member",
        method: "PATCH",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/members/{id}/",
        requiresHackathonId: true,
        requiresId: true,
        sampleBody: JSON.stringify({ player_label: "Blue-1", is_active: true }, null, 2),
      },
      {
        id: "members-delete",
        name: "Remove member",
        method: "DELETE",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/members/{id}/",
        requiresHackathonId: true,
        requiresId: true,
      },
      {
        id: "members-block",
        name: "Block member",
        method: "POST",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/members/{id}/block/",
        requiresHackathonId: true,
        requiresId: true,
        sampleBody: JSON.stringify({ reason: "Cheating" }, null, 2),
      },
      {
        id: "members-unblock",
        name: "Unblock member",
        method: "POST",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/members/{id}/unblock/",
        requiresHackathonId: true,
        requiresId: true,
      },
      {
        id: "members-profile",
        name: "Patch member profile",
        method: "PATCH",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/members/{id}/profile/",
        requiresHackathonId: true,
        requiresId: true,
        sampleBody: JSON.stringify({ name: "Ali", last_name: "Khan" }, null, 2),
      },
    ],
  },
  {
    id: "teams",
    title: "7. Teams",
    description: "Team admin for an event.",
    endpoints: [
      {
        id: "teams-platform-list",
        name: "List all teams (platform)",
        method: "GET",
        pathTemplate: "/api/haas/teams/",
        description:
          "Root/system.admin. Optional: search, status, register_as, hackathon.",
      },
      {
        id: "teams-list",
        name: "List teams",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/teams/",
        requiresHackathonId: true,
      },
      {
        id: "teams-create",
        name: "Create team",
        method: "POST",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/teams/",
        requiresHackathonId: true,
        sampleBody: JSON.stringify(
          { name: "Red-01", description: "", register_as: "red", affiliation: "" },
          null,
          2,
        ),
      },
      {
        id: "teams-attach",
        name: "Attach existing team",
        method: "POST",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/teams/attach/",
        requiresHackathonId: true,
        sampleBody: JSON.stringify({ team_id: "<team-uuid>" }, null, 2),
      },
      {
        id: "teams-get",
        name: "Get team",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/teams/{id}/",
        requiresHackathonId: true,
        requiresId: true,
      },
      {
        id: "teams-patch",
        name: "Update team",
        method: "PATCH",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/teams/{id}/",
        requiresHackathonId: true,
        requiresId: true,
        sampleBody: JSON.stringify({ name: "Red-01-renamed" }, null, 2),
      },
      {
        id: "teams-delete",
        name: "Detach team",
        method: "DELETE",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/teams/{id}/",
        requiresHackathonId: true,
        requiresId: true,
      },
      {
        id: "teams-approve",
        name: "Approve team members",
        method: "POST",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/teams/{id}/approve-members/",
        requiresHackathonId: true,
        requiresId: true,
        sampleBody: JSON.stringify(
          { membership_id: "<membership-uuid>", approved: true },
          null,
          2,
        ),
      },
      {
        id: "teams-members",
        name: "List/add team members",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/teams/{id}/members/",
        requiresHackathonId: true,
        requiresId: true,
      },
      {
        id: "teams-members-post",
        name: "Add team member",
        method: "POST",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/teams/{id}/members/",
        requiresHackathonId: true,
        requiresId: true,
        sampleBody: JSON.stringify({ user: "<user-uuid>" }, null, 2),
      },
      {
        id: "teams-members-remove",
        name: "Remove team member",
        method: "DELETE",
        pathTemplate:
          "/api/haas/hackathons/{hackathonId}/teams/{id}/members/{extraId}/",
        requiresHackathonId: true,
        requiresId: true,
        requiresExtraId: true,
        extraIdLabel: "membershipId",
      },
      {
        id: "teams-block",
        name: "Block team",
        method: "POST",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/teams/{id}/block/",
        requiresHackathonId: true,
        requiresId: true,
      },
      {
        id: "teams-unblock",
        name: "Unblock team",
        method: "POST",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/teams/{id}/unblock/",
        requiresHackathonId: true,
        requiresId: true,
      },
    ],
  },
  {
    id: "challenges",
    title: "8. Challenges",
    description:
      "Smart list: empty hackathon ID + Root/system.admin → all challenges; otherwise event-scoped.",
    endpoints: [
      {
        id: "challenge-list-smart",
        name: "List challenges (smart)",
        method: "GET",
        pathTemplate: "/api/haas/challenge-list",
        description:
          "Leave Hackathon ID empty for Root/system.admin to fetch ALL challenges. Set Hackathon ID to scope to one event (challenge-admin). Optional query: search, category, is_active.",
        requiresHackathonId: false,
      },
      {
        id: "challenges-list",
        name: "List challenge links",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/challenges/",
        requiresHackathonId: true,
      },
      {
        id: "challenges-create",
        name: "Create challenge link",
        method: "POST",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/challenges/",
        requiresHackathonId: true,
        sampleBody: JSON.stringify({ challenge: "<challenge-uuid>" }, null, 2),
      },
      {
        id: "challenges-approve",
        name: "Approve challenge link",
        method: "POST",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/challenges/{id}/approve/",
        requiresHackathonId: true,
        requiresId: true,
      },
      {
        id: "challenges-delete",
        name: "Soft-delete challenge link",
        method: "DELETE",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/challenges/{id}/",
        requiresHackathonId: true,
        requiresId: true,
      },
      {
        id: "challenge-admin-list",
        name: "Challenge admin list (event)",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/challenge-admin/",
        requiresHackathonId: true,
      },
      {
        id: "challenge-admin-create",
        name: "Challenge admin create",
        method: "POST",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/challenge-admin/",
        requiresHackathonId: true,
        sampleBody: JSON.stringify(
          {
            name: "Web 101",
            description: "Find the flag",
            is_dynamic: true,
            challenge_for: "hackathon",
            category: "<category-uuid>",
            difficulty_level: "<difficulty-uuid>",
            challenge_type: "<type-uuid>",
            docker: {
              image_name: "web101",
              image_tag: "latest",
              machine_name: "web101-box",
              docker_type: "docker",
              os: "Linux",
              port: 80,
              flag_num: 1,
              time_limit: 120,
            },
          },
          null,
          2,
        ),
      },
      {
        id: "challenge-admin-get",
        name: "Challenge admin get",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/challenge-admin/{id}/",
        requiresHackathonId: true,
        requiresId: true,
      },
      {
        id: "challenge-admin-patch",
        name: "Challenge admin update",
        method: "PATCH",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/challenge-admin/{id}/",
        requiresHackathonId: true,
        requiresId: true,
        sampleBody: JSON.stringify(
          {
            name: "Web 101 updated",
            docker_port: 8080,
            clear_file: false,
          },
          null,
          2,
        ),
      },
      {
        id: "challenge-admin-delete",
        name: "Challenge admin delete",
        method: "DELETE",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/challenge-admin/{id}/",
        requiresHackathonId: true,
        requiresId: true,
      },
      {
        id: "platform-challenges-list",
        name: "Platform challenges (all)",
        method: "GET",
        pathTemplate: "/api/haas/challenges/",
        description:
          "Root / system.admin only. Lists every challenge. Optional query: hackathon=<uuid> to filter.",
        requiresHackathonId: false,
      },
      {
        id: "platform-challenges-create",
        name: "Platform challenge create (JSON or multipart)",
        method: "POST",
        pathTemplate: "/api/haas/challenges/",
        requiresHackathonId: false,
        sampleBody: JSON.stringify(
          {
            name: "Platform lab",
            is_dynamic: true,
            docker: {
              machine_name: "lab-vm",
              docker_type: "vm",
              os: "Linux",
              port: 22,
              flag_num: 1,
            },
            note: "For uploads use multipart: file + docker_media",
          },
          null,
          2,
        ),
      },
      {
        id: "platform-challenges-get",
        name: "Platform challenge get",
        method: "GET",
        pathTemplate: "/api/haas/challenges/{id}/",
        requiresHackathonId: false,
        requiresId: true,
      },
      {
        id: "questions-list",
        name: "List questions",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/challenge-admin/{id}/questions/",
        requiresHackathonId: true,
        requiresId: true,
      },
      {
        id: "answers-list",
        name: "List answers",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/challenge-admin/{id}/answers/",
        requiresHackathonId: true,
        requiresId: true,
      },
      {
        id: "attempt-overrides",
        name: "Attempt overrides",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/attempt-overrides/",
        requiresHackathonId: true,
      },
      {
        id: "categories-list",
        name: "Event categories",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/categories/",
        requiresHackathonId: true,
      },
      {
        id: "categories-approve",
        name: "Approve category",
        method: "POST",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/categories/{id}/approve/",
        requiresHackathonId: true,
        requiresId: true,
      },
    ],
  },
  {
    id: "ops",
    title: "9. Scores, logs, notifications, machines",
    description: "Run-day operations.",
    endpoints: [
      {
        id: "scores",
        name: "List scores",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/scores/",
        requiresHackathonId: true,
      },
      {
        id: "scores-delete",
        name: "Soft-delete score",
        method: "DELETE",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/scores/{id}/",
        requiresHackathonId: true,
        requiresId: true,
      },
      {
        id: "activity-logs",
        name: "Activity logs",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/activity-logs/",
        requiresHackathonId: true,
      },
      {
        id: "audit-logs",
        name: "Audit logs",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/audit-logs/",
        requiresHackathonId: true,
      },
      {
        id: "notifications-list",
        name: "List notifications",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/notifications/",
        requiresHackathonId: true,
      },
      {
        id: "notifications-create",
        name: "Send notification",
        method: "POST",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/notifications/",
        requiresHackathonId: true,
        sampleBody: JSON.stringify(
          {
            title: "Round 2",
            message: "Starts now",
            team: null,
            type: "staff",
            category: "public",
            users_for: [],
          },
          null,
          2,
        ),
      },
      {
        id: "machines",
        name: "List machines",
        method: "GET",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/machines/",
        requiresHackathonId: true,
      },
      {
        id: "machines-bulk-spawn",
        name: "Bulk spawn",
        method: "POST",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/machines/bulk-spawn/",
        requiresHackathonId: true,
        sampleBody: JSON.stringify({ challenge_id: "<uuid>", team_ids: [] }, null, 2),
      },
      {
        id: "machines-bulk-stop",
        name: "Bulk stop",
        method: "POST",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/machines/bulk-stop/",
        requiresHackathonId: true,
        sampleBody: JSON.stringify({ machine_ids: [] }, null, 2),
      },
      {
        id: "machines-stop",
        name: "Stop machine",
        method: "POST",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/machines/{id}/stop/",
        requiresHackathonId: true,
        requiresId: true,
      },
      {
        id: "machines-block",
        name: "Block machine",
        method: "POST",
        pathTemplate: "/api/haas/hackathons/{hackathonId}/machines/{id}/block/",
        requiresHackathonId: true,
        requiresId: true,
      },
    ],
  },
];

export function buildEndpointPath(
  template: string,
  values: {
    hackathonId?: string;
    id?: string;
    extraId?: string;
    query?: string;
  },
): string {
  let path = template
    .replaceAll("{hackathonId}", values.hackathonId?.trim() || "{hackathonId}")
    .replaceAll("{id}", values.id?.trim() || "{id}")
    .replaceAll("{extraId}", values.extraId?.trim() || "{extraId}");

  const query = values.query?.trim();
  if (query) {
    path += query.startsWith("?") ? query : `?${query}`;
  }

  return path;
}
